### ISSUE TITLE
Not found : @clever/discovery

### ISSUE THREAD

**Issue by runpengchensc** [Clever/gearman-admin#98]
It keep saying Not found : @clever/discovery. And also I can't find on the npm. Do I need to install based on your github repo?

**Comment by nathanleiby** [comment]
Discovery is cross-language pattern that we use for service-discovery. For example, the corresponding discovery implementation is Node is here: https://github.com/Clever/discovery-node

I believe we previously had discovery as a private repo and made it public, but the corresponding NPM package is still private (and shouldn't be). We can work on fixing this, but in the meantime, I'd suggest installing directly from the above repo.

You could also modify these lines to directly set the host and port for your gearman client.
https://github.com/Clever/gearman-admin/blob/99b885d920c23dd7b2d10f721deb5b57ade3eaa5/routes.coffee#L58-L63

**Comment by runpengchensc** [comment]
Thanks. It works for me. But when I setup and run it, it give me this error. `{ [TimeoutError: Missing credentials in config]
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: Mon Sep 12 2016 14:17:24 GMT-0700 (PDT),
  retryable: true,
  originalError: 
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: Mon Sep 12 2016 14:17:24 GMT-0700 (PDT),
     retryable: true,
     originalError: 
      { message: 'Missing credentials in config',
        code: 'CredentialsError',
        time: Mon Sep 12 2016 14:17:23 GMT-0700 (PDT),
        retryable: true,
        originalError: [Object] } } } null
`

I try to search in the Readme, but I got nothing. Thanks.

**Comment by samfishman** [comment]
It seems like you have not configured your AWS credentials – this is unfortunately not well documented. If you provide `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (as well as `AWS_DYNAMO_REGION` if the default of us-west-1 doesn't work for you) as environment variables, you should be able to get things working. We use AWS to store session data in DynamoDB.

**Comment by runpengchensc** [comment]
Hi Sam,

Yes, I know the problem comes from AWS. However, I would like to set up on
the localhost, my own machine. Is it possible to decouple the AWS?

Thanks,
Runpeng

**Comment by samfishman** [comment]
Unfortunately we don't support that configuration, but you can modify the code to decouple it if you edit the session setup in server.coffee (see line 41) to store session data in-memory (AWS is only used for sessions).

**Comment by runpengchensc** [comment]
Hi Sam,

Thank you very much. I will try it.

Thanks again,
Runpeng
